name: Validate sources using PyLint
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  setup-python:
    name: Setup PyLint ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python:
        - 'python-3.9'
        - 'python-3.10'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python Pylin GitHub Action
        uses: fylein/python-pylint-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc main models config
