name: Validate sources using PyLint
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  lint:
    name: Setup PyLint ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python:
        - 'python-3.9'
        - 'python-3.10'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Executing PyLint using GitHub Action
        uses: fylein/python-pylint-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc main models config


  build:
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tech2heal:latest
